# Generated by Django 5.0 on 2025-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='property',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
